import { StyleSheet } from "react-native";
import { moderateScale, scale } from "react-native-size-matters";

export const mapDelivaryStyles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: moderateScale(16),
    paddingBottom: moderateScale(40),
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '600',
  },
  loadingSubtext: {
    fontSize: 14,
    opacity: 0.7,
  },
  titleContainer: {
    alignItems: 'center',
    marginTop: moderateScale(60),
    marginBottom: moderateScale(24),
    gap: 8,
  },
  mainTitle: {
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  subtitle: {
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
   backButton: {
     width: 40,
     height: 40,
     top:scale(6),
    marginHorizontal: 20,
    position: 'absolute',
    zIndex: 100,  
     borderRadius: 20,
     borderColor: 'white',
     borderStyle: 'solid',
     borderWidth: 1,
     overflow: 'hidden',
     justifyContent: 'center',
     alignItems: 'center',
   },
  backButtonText: {
    fontSize: moderateScale(16),
    fontWeight: '600',
  },
  mapContainer: {
    position: 'relative',
    marginBottom: moderateScale(32),
  },
  mapBox: {
    width: '100%',
    height: moderateScale(300),
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  mapInBox: {
    flex: 1,
  },
  mapLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  mapInfoBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  mapInfoText: {
    fontSize: moderateScale(13),
    fontWeight: '600',
  },
  expandButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  expandButtonText: {
    fontSize: 24,
    fontWeight: '600',
  },
  fullscreenContainer: {
    flex: 1,
    position: 'relative',
  },
  fullscreenButton: {
    position: 'absolute',
    top:moderateScale(80

    ),
    left: moderateScale(5),
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  fullscreenButtonText: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: moderateScale(20),
    fontWeight: '700',
    marginBottom: moderateScale(16),
    letterSpacing: 0.3,
  },
  optionsWrapper: {
    gap: moderateScale(16),
  },
  calculatingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(12),
    backgroundColor: 'rgba(0, 102, 204, 0.1)',
    borderRadius: 12,
    gap: 12,
    marginBottom: moderateScale(8),
  },
  calculatingBannerText: {
    fontSize: moderateScale(13),
    fontWeight: '500',
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: moderateScale(20),
    paddingHorizontal: moderateScale(16),
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    minHeight: moderateScale(110),
    position: 'relative',
  },
  iconContainer: {
    flexDirection: 'column',
    width: moderateScale(65),
    height: moderateScale(65),
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(12),
    gap: 6,
  },
  chainName: {
    fontSize: moderateScale(10),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  infoSection: {
    flex: 1,
    gap: 8,
  },
  sectionLabel: {
    fontSize: moderateScale(11),
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    opacity: 0.6,
  },
  dataGroup: {
    flexDirection: 'column',
    gap: 6,
  },
  dataBadge: {
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(7),
    borderRadius: 10,
    marginRight: moderateScale(3),
    borderWidth: 1.5,
  },
  dataText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  calculatingText: {
    fontSize: moderateScale(12),
    fontWeight: '500',
  },
  arrowContainer: {
    marginLeft: moderateScale(8),
  },
  arrow: {
    fontSize: moderateScale(36),
    fontWeight: '200',
  },
  bestDealBadge: {
    position: 'absolute',
    top: -8,
    right: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  bestDealText: {
    color: '#FFFFFF',
    fontSize: moderateScale(11),
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  closestBadge: {
    position: 'absolute',
    top: -8,
    right: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  closestText: {
    color: '#FFFFFF',
    fontSize: moderateScale(11),
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  infoFooter: {
    marginTop: moderateScale(24),
    padding: moderateScale(16),
    borderRadius: 14,
    alignItems: 'center',
      shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  footerText: {
    fontSize: moderateScale(13),
    fontWeight: '500',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  emptyState: {
    padding: moderateScale(32),
    alignItems: 'center',
    gap: 12,
  },
  emptyStateText: {
    fontSize: moderateScale(15),
    fontWeight: '500',
    textAlign: 'center',
  },
    tabBarBlur: {
    ...StyleSheet.absoluteFillObject,
  },
});