import { getFontSize, hp, wp } from "@/components/utils/dimenstions";
import { StyleSheet } from "react-native";
import { moderateScale } from "react-native-size-matters";

export const createStyles = ({

  isSimpleMode,
}: {
  isSimpleMode: boolean;
}) =>
    StyleSheet.create({
    container: { flex: 1 },

  backgroundImage: { flex: 1, width: '100%', height: '100%' },
  scrollContent: { paddingBottom: 100 },
  imageContainer: {
    backgroundColor: 'white',
    marginTop: wp(15),
    alignItems: 'center',
    paddingVertical: 0,
    marginBottom: hp(2),
    alignSelf: 'center',
    height: hp(40),
    width: wp(94),
    position: 'relative',
    shadowColor: '#000',
    overflow: 'hidden',
    borderRadius: wp(4),
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: isSimpleMode ? 3 : 1,
    borderColor: isSimpleMode? "#000000" : '#666666',
  },
  productImage: { height: '100%', width: '100%', resizeMode: 'contain' },
  detailsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    width: wp(95),
    alignSelf: 'center',
    borderRadius: wp(4),
    padding: 20,
    marginBottom: hp(2),
        borderWidth: isSimpleMode ? 3 : 1,
    borderColor: isSimpleMode? "#000000" : '#666666',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  productName: { fontSize: isSimpleMode ? moderateScale(30) : moderateScale(26), fontWeight: 'bold', color: '#333', marginBottom: 5 },
  brandText: { fontSize: 16, color: '#666', marginBottom: 8 },
  categoryContainer: { marginBottom: 12 },
  categoryText: { fontSize: 14, color: '#666' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: hp(1) },
  starsContainer: { flexDirection: 'row', marginRight: 10 },
  star: { marginRight: 2 },
  ratingText: { fontSize: 16, color: '#1F2937' },
  priceContainer: { marginBottom: hp(1) },
  priceLabel: { fontSize: 14, color: '#666', marginBottom: 4 },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  unitContainer: { flexDirection: 'column', alignItems: 'flex-start', marginBottom: hp(2) },
  price: { fontSize: 32, fontWeight: 'bold', color: '#006D77' },

  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 10 },
  quantitySection: { marginBottom: 25 },
  quantityContainer: { flexDirection: 'row', alignItems: 'center' },
  quantityButton: {
    backgroundColor: 'rgba(143,228,201,1)',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonText: { fontSize: 20, fontWeight: 'bold', color: '#1F2937' },
  quantityText: { fontSize: 20, fontWeight: 'bold', marginHorizontal: 20, color: '#333' },
  chartContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: wp(4),
    width: wp(95),
    alignSelf: 'center',
    padding: 20,
    marginBottom: hp(2),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  chartTitle: { fontSize: isSimpleMode? 25 : 20, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  chartSubtitle: { fontSize: 14, color: '#666', marginBottom: 20 },
  pointerLabel: {
    backgroundColor: 'rgba(143, 228, 201, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  pointerLabelText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
  pointerLabelMonth: { color: 'white', fontSize: 12, opacity: 0.9 },
  trendIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.1)',
  },
  trendText: { color: '#4CAF50', fontSize: 14, fontWeight: '600', marginLeft: 6 },
  retailsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: wp(4),
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp(95),
    alignSelf: 'center',
    padding: 15,
    paddingTop:20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  leftSection: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  storeInfo: { flexDirection: 'row', alignItems: 'center', marginRight: 12 },
  rightSection: { alignItems: 'flex-end', paddingHorizontal: 5, textAlign: 'center', justifyContent: 'center' },
  retailImages: { width: wp(10), height: wp(10) },
  retailText: {
    paddingLeft: wp(2),
    fontWeight: 'bold',
    fontSize: isSimpleMode ?getFontSize(20) : getFontSize(16),
    color: '#1F2937',
  },
  discountText: { color: '#1F2937', fontWeight: 'bold', fontSize: 12 },
  retailPrice: {
    fontSize:  isSimpleMode ?getFontSize(22) : getFontSize(20),
    fontWeight: 'bold',
    color: '#006D77',
    marginBottom: 2,
  },
  originalPrice: {
    fontSize: getFontSize(18),
    color: '#999',
    textDecorationLine: 'line-through',
  },
  discountContainer: {
    backgroundColor: 'rgba(143,228,201,1)',
    padding: 5,
    borderRadius: 5,
    alignSelf: 'center',
  },
  OneRetailBox: {
    minHeight:moderateScale(70),
    paddingVertical: hp(1),
    paddingHorizontal:hp(1),
    marginBottom:10,
    borderTopColor:'black',
    borderTopWidth: isSimpleMode ? 3 : 1,
    flexDirection: 'row',
    borderWidth: isSimpleMode ? 3 : 1,
    borderRadius:15,
        overflow:'hidden',
  },
  retailTitle: {
    fontSize: isSimpleMode? 24 : 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { fontSize: getFontSize(18), fontWeight: '500', color: '#333' },
  notFoundContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  notFoundText: {
    fontSize: getFontSize(20),
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  retryButton: { marginTop: 16, padding: 12 },
  retryButtonText: { fontSize: 16, fontWeight: '600' },
  blurContainer: {
    position: 'absolute',
    bottom: wp(7),
    width: wp(95),
    alignSelf: 'center',
    borderRadius: 15,
    padding: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  cartButton: { justifyContent: 'center', flexDirection: 'row', alignItems: 'center' },
  cartButtonText: { fontWeight: '600', fontSize: 20, marginLeft: 8 },
  heartOverlay: {
    position: 'absolute',
    top: hp(1),
    right: wp(2),
    zIndex: 10,
  },
  bestDealBox: {
    borderRadius: 16,
    padding: 16,
    paddingHorizontal:10,
    marginVertical: hp(1),
    borderWidth: isSimpleMode ? 5 :2,
    width: '100%',

  },
  bestDealHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    paddingBottom: 8,
  },
  bestDealLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bestDealLabel: {
    fontSize: isSimpleMode?getFontSize(16) : getFontSize(12),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  bestDealDiscountPill: {
    backgroundColor: 'rgba(143,228,201,1)',
    paddingHorizontal: isSimpleMode? 12: 8,
    paddingVertical:  isSimpleMode? 5: 2,
    borderRadius: 5,
  },
  bestDealDiscountText: {
    fontSize: isSimpleMode ? moderateScale(14): moderateScale(10) ,
    fontWeight: 'bold',
  },
  bestDealContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bestDealChainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flex: 1,
  },
  bestDealLogo: {
    width: wp(10), 
    height: wp(10),
    borderRadius: 8,
  },
  bestDealChainName: {
    fontSize: getFontSize(20), 
    fontWeight: 'bold',
  },
  bestDealPriceStack: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    flexDirection:'row',
    gap:10
  },
  priceWrapper: {
    alignItems: 'flex-end',
  },
  bestDealPriceMain: {
    fontSize: isSimpleMode?getFontSize(22) : getFontSize(20),
    fontWeight: '900',
    
    
    lineHeight: 30,
  },
  bestDealPriceSub: {
    fontSize: getFontSize(14),
    fontWeight: '600',
    opacity: 0.8,
    marginTop: 2,
  },
  originalPriceSmall: {
    fontSize: getFontSize(13),
    textDecorationLine: 'line-through',
    opacity: 0.6,
    marginTop: -2,
    marginBottom: 2,
  },
   bestDealLabelColumn: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  timerText: {
    fontSize: isSimpleMode? moderateScale(12) :moderateScale(9),
    fontWeight: '600',
  },
  discountBadge: {
  position: 'absolute',
  zIndex: 500,
  transform: [{ rotateZ: '-0.785398rad' }],
  left: -67,
  top:-10,
  minWidth:150,
  paddingHorizontal: 10,
  paddingVertical: 3,
  alignItems: 'center',
},
discountBadgeText: {
  fontSize: moderateScale(15),
  fontWeight: "600",
},
});